server:
  port: 9094

spring:
  data:
    mongodb:
     url: mongodb://localhost:27017/orderdb
     host: localhost
     port: 27017
     database: orderdb
     repositories:
      enabled: true
    
  application:
    name: ORDER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  